# Notebook 02 — Data Preprocessing and Cleaning

## Overview
This notebook covers data preprocessing and cleaning
on the Titanic dataset in preparation for building
classification models in Notebook 03.

## What This Notebook Covers
- Handling missing values
- Dropping irrelevant columns
- Encoding categorical variables
- Feature scaling
- Saving cleaned dataset as titanic_clean.csv

## Dataset
- **Name:** Titanic Survival Dataset
- **Rows:** 891 passengers
- **Columns:** 12
- **Source:** datasciencedojo GitHub

## Author
- **Name:** Martin James
- **GitHub:** github.com/M20Jay
- **Goal:** ML Engineer Roadmap — Notebook 02 of 10
```

## Section 1 — Import Libraries

In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
print("library successfully loaded")

library successfully loaded

## Section 2 — Loading Data

In [41]:
df=pd.read_csv("titanic.csv")
print(df.shape)
print("\n First 5 rows")
print(df.head())

(891, 12)

 First 5 rows
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

## Section 3 — Inspecting the Data

In [42]:
# Data types and non-null counts
print("=== Dataset Info ===")
df.info()

=== Dataset Info ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [43]:
# Summary statistics
print("=== Summary Statistics ===")
df.describe()

=== Summary Statistics ===

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [44]:
# Missing value per column
print("=== Missing Values ===")
missing = df.isnull().sum()
missing_percentage = df.isnull().sum()/len(df)*100
missing_table= pd.DataFrame({
    "Missing Values": missing,
    "Percentage": missing_percentage
})

print(missing_table[missing_table["Missing Values"]>0])

=== Missing Values ===
          Missing Values  Percentage
Age                  177   19.865320
Cabin                687   77.104377
Embarked               2    0.224467

## Section 4 — Handling Missing Values

In [45]:
# Fill Age with median — right skewed distribution
df['Age'].fillna(df['Age'].median(),inplace=True)

In [46]:
# Drop Cabin — 77% missing, too many to fill
df.drop(columns=["Cabin"], inplace = True)

In [47]:
# Fill Embarked with mode — only 2 missing
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
print(" Embarked missing values:", df["Embarked"].isnull().sum())

 Embarked missing values: 0

In [48]:
# Confirm no missing values remain
print("=== Missing Values After Cleaning ===")
print(df.isnull().sum())

=== Missing Values After Cleaning ===
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

## Section 5 — Encoding Categorical Variables

In [49]:
# Encode Sex — female=0, male=1
df['Sex']= df['Sex'].map({'female':1, 'male':0})
print("Sex encoded:")
print(df["Sex"].value_counts())

Sex encoded:
Sex
0    577
1    314
Name: count, dtype: int64

In [50]:
# One Hot Encode Embarked
df= pd.get_dummies(df, columns=["Embarked"], drop_first =True)
print(" Embarked Encoded:")
print(df.columns.tolist())

 Embarked Encoded:
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Embarked_Q', 'Embarked_S']

In [51]:
# Confirm encoding
print("=== Dataset After Encoding ===")
print(df.shape)
print(df.head())

=== Dataset After Encoding ===
(891, 12)
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0
2                             Heikkinen, Miss. Laina    1  26.0      0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0
4                           Allen, Mr. William Henry    0  35.0      0      0

             Ticket     Fare  Embarked_Q  Embarked_S
0         A/5 21171   7.2500       False        True
1          PC 17599  71.2833       False       False
2  STON/O2. 3101282   7.9250       False        True
3            113803  53.1000       False        True
4            373450   8.0500       False        True

In [52]:
# Checking current Sex values
print("Sex unique values:")
print(df['Sex'].unique())

Sex unique values:
[0 1]

In [53]:
#Checking current Embarked Values
#print(df['Embarked'].unique())

In [54]:
#Confirm everything:
print("=== Dataset After Encoding ===")
print("Shape:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())
print("\nFirst 3 rows:")
df.head(3)

=== Dataset After Encoding ===
Shape: (891, 12)

Missing values:
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked_Q     0
Embarked_S     0
dtype: int64

First 3 rows:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,False,False
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,False,True

In [55]:
# Force drop Cabin
if 'Cabin' in df.columns:
    df.drop(columns=['Cabin'], inplace=True)
    print("Cabin dropped ✅")
else:
    print("Cabin already gone ✅")

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

Cabin already gone ✅
Shape: (891, 12)
Columns: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Embarked_Q', 'Embarked_S']

## Section 6 — Feature Scaling

In [56]:
from sklearn.preprocessing import StandardScaler
scaler =StandardScaler()
df[['Age', 'Fare']]= scaler.fit_transform(df[['Age','Fare']])
print("===After Scaling")
print(df[["Age", "Fare"]].describe().round(2))

===After Scaling
          Age    Fare
count  891.00  891.00
mean     0.00    0.00
std      1.00    1.00
min     -2.22   -0.65
25%     -0.57   -0.49
50%     -0.10   -0.36
75%      0.43   -0.02
max      3.89    9.67

## Section 7 — Saving the Clean Dataset

In [57]:
# Save cleaned Dataset
df.to_csv('titanic_clean.csv', index= False)

print("===Dataset saved===")
print("File: titanic_clean.csv ✅")
print("Shape :", df.shape)
print("Colomns:", df.columns.tolist())

===Dataset saved===
File: titanic_clean.csv ✅
Shape : (891, 12)
Colomns: ['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Embarked_Q', 'Embarked_S']

## Section 8 — Key Findings Summary
Summary of all preprocessing steps completed in this notebook.

In [58]:
print("=" *50)
print("Preprocessing Summary")
print("=" *50)
print(f" Dataset Shape:, {df.shape}")
print(f"Total missing values: {df.isnull().sum()}")
print(f"f\n Steps completed:")
print(f"Total missing values: {df.isnull().sum().sum()}")
print(f"\nSteps completed:")
print(f"  ✅ Filled Age with median")
print(f"  ✅ Dropped Cabin (77% missing)")
print(f"  ✅ Filled Embarked with mode")
print(f"  ✅ Encoded Sex (female=0, male=1)")
print(f"  ✅ One Hot Encoded Embarked")
print(f"  ✅ Scaled Age and Fare")
print(f"  ✅ Saved as titanic_clean.csv")
print(f"\nReady for Notebook 03 ✅")
print("=" * 50)

==================================================
Preprocessing Summary
==================================================
 Dataset Shape:, (891, 12)
Total missing values: PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked_Q     0
Embarked_S     0
dtype: int64
f
 Steps completed:
Total missing values: 0

Steps completed:
  ✅ Filled Age with median
  ✅ Dropped Cabin (77% missing)
  ✅ Filled Embarked with mode
  ✅ Encoded Sex (female=0, male=1)
  ✅ One Hot Encoded Embarked
  ✅ Scaled Age and Fare
  ✅ Saved as titanic_clean.csv

Ready for Notebook 03 ✅
==================================================